@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttributeIconSize 0

CentralAlarma "1" --- "1..*" Edificio : conectada
Edificio "1" --- "1" Sensores : tiene
Sensores "0..1" --- "1" Bomberos : llama
Sensores "1" --- "1" Policia : llama

class CentralAlarma {

}

enum Edificio <<enumeration>> {
    alarmaIncendio
    alarmaRobo
}

enum Sensores <<enumeration>> {
    sensorFuego
    sensorRobo
}

class Bomberos {

}

class Policia {

}

@enduml