@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttributeIconSize 0

Persona "1" --- "1" Estudiante : entra universidad
Estudiante "1" --- "1..*" Asignaturas : matricula
Estudiante "1" --- "0..1" Becario : opta
Becario "1" --- "1..*" Asignaturas : matricula

class Persona {
    - DNI : Varchar
    - Nombre : String
    - Dirección : Varchar
    - EstadoCivil : String
}

class Estudiante {

}

class Asignaturas {
    - CódigoAS : integer
    - Nombre : String
    - Profesor : String
    - Curso : integer
}

class Becario {
    - CódigoBE : integer
    - Importe : integer
}

enum Aplicaciones <<enumeration>> {
    DarAltaNuevasPersonasYAsignaturas
    MatriculaciónEstudiantes
    RegistrarNotasEstudiantes
    AlumnosMatriculados
    AsignaturasMatriculadoAlumno
    NotasAsignatura
}

@enduml